--local nvim_lsp = require 'lspconfig'
--
---- Workaround for LSP: rust_analyzer: -32802: server cancelled the request
---- https://github.com/neovim/neovim/issues/30985#issuecomment-2447329525
--for _, method in ipairs({ 'textDocument/diagnostic', 'workspace/diagnostic' }) do
--    local default_diagnostic_handler = vim.lsp.handlers[method]
--    vim.lsp.handlers[method] = function(err, result, context, config)
--        if err ~= nil and err.code == -32802 then
--            return
--        end
--        return default_diagnostic_handler(err, result, context, config)
--    end
--    return default_diagnostic_handler(err, result, context, config)
--end

